// items.js

export const ITEMS = {
  food: [
    { id: 1, name: "Maggi Masala", price: 20 },
  { id: 2, name: "Maggi Veggie Pack", price: 25 },
  { id: 3, name: "Maggi Chicken Pack", price: 30 },
  { id: 4, name: "Cup Noodles", price: 35 },
  { id: 5, name: "Instant Oats", price: 40 },
  { id: 6, name: "Poha Cup", price: 30 },
  { id: 7, name: "Soup Packet", price: 25 },
  { id: 8, name: "Chips (Assorted)", price: 20 },
  { id: 9, name: "Biscuits Pack", price: 15 },
  { id: 10, name: "Bread Loaf", price: 25 },
  { id: 11, name: "Peanut Butter", price: 60 },
  { id: 12, name: "Jam", price: 35 },
  { id: 13, name: "Milk Powder", price: 120 },
  { id: 14, name: "Cold Drink (500ml)", price: 35 },
  { id: 15, name: "Juice Box", price: 25 },
  ],
  grocery: [
    { id: 16, name: "Toothpaste", price: 45 },
  { id: 17, name: "Toothbrush", price: 30 },
  { id: 18, name: "Soap Bar", price: 25 },
  { id: 19, name: "Shampoo Sachet Pack", price: 20 },
  { id: 20, name: "Hair Oil (Small)", price: 40 },
  { id: 21, name: "Laundry Detergent (Small Pack)", price: 30 },
  { id: 22, name: "Tissue Box", price: 35 },
  { id: 23, name: "Room Freshener", price: 75 },
  { id: 24, name: "Hand Sanitizer", price: 50 },
  { id: 25, name: "Face Wash", price: 70 },
  { id: 26, name: "Detergent Bar", price: 20 },
  { id: 27, name: "Washing Powder", price: 60 },
  ],
  stationery: [
    { id: 28, name: "A4 Printing (Per Page)", price: 5 },
  { id: 29, name: "Color Printing (Per Page)", price: 15 },
  { id: 30, name: "Photocopy (Per Page)", price: 2 },
  { id: 31, name: "Notebook", price: 40 },
  { id: 32, name: "Pen (Blue/Black)", price: 10 },
  { id: 33, name: "Highlighter", price: 25 },
  { id: 34, name: "Stapler", price: 40 },
  { id: 35, name: "Staple Pins Pack", price: 15 },
  { id: 36, name: "Folder File", price: 30 },
  { id: 37, name: "USB Drive (16GB)", price: 350 },
  { id: 38, name: "Marker", price: 20 },
  { id: 39, name: "Paper Clips Pack", price: 10 },
  ],
  cafe: [
      { id: 40, name: "Tea (Hot)", price: 15 },
  { id: 41, name: "Coffee (Hot)", price: 20 },
  { id: 42, name: "Cold Coffee", price: 45 },
  { id: 43, name: "Sandwich", price: 50 },
  { id: 44, name: "Pasta", price: 70 },
  { id: 45, name: "Burger", price: 60 },
  { id: 46, name: "Fries", price: 40 },
  { id: 47, name: "Momos", price: 50 },
  { id: 48, name: "Spring Rolls", price: 45 },
  { id: 49, name: "Paneer Wrap", price: 65 },
  { id: 50, name: "Water Bottle (1L)", price: 20 },

  ],
};
